### ISSUE TITLE
Running ./emc_vnx_stat.py get error's

### ISSUE THREAD

**Issue by stojke** [ktelep/EMC-Zabbix-Integration#15]
Hi, I do everything as you mention in your readme file, but I get errors below if I try to run script as a zabbix user:

bash-4.1$ ./emc_vnx_stats.py --serial FCN2USOMESERIAL --ecom_user admin  --ecom_ip 192.168.1.1 --ecom_pass MYpassword --array
Traceback (most recent call last):
  File "./emc_vnx_stats.py", line 661, in <module>
    main()
  File "./emc_vnx_stats.py", line 587, in main
    setup_logging(log_file)
  File "./emc_vnx_stats.py", line 572, in setup_logging
    log_file, maxBytes=5120000, backupCount=5)
  File "/usr/lib64/python2.6/logging/handlers.py", line 112, in **init**
    BaseRotatingHandler.**init**(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.6/logging/handlers.py", line 64, in **init**
    logging.FileHandler.**init**(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.6/logging/**init**.py", line 835, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib64/python2.6/logging/__init__.py", line 854, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/emc_vnx_stats.log'

Also, when I try to catch log from discovery file I got this: 
2016-06-28 12:37:06,996 INFO 16364 Building WBEM Connection to https://192.168.1.1:5989
2016-06-28 12:37:06,996 INFO 16364 Volume discovery started
2016-06-28 12:37:07,054 ERROR 16364 Uncaught exception: Authorization Required

Can you please give me some hint? My EMC storage are EMC VNXi 1600, zabbix version 3.03

Thank you,

**Comment by ktelep** [comment]
As of today the VNXe platform is not supported. It is on the list to be
added along with Unity support but I do not have a release date yet.
