### ISSUE TITLE
error of  use ecom_vnx_manage.py add new spa  to ECOM server 

### ISSUE THREAD

**Issue by fooltux** [ktelep/EMC-Zabbix-Integration#18]
when I  use ecom_vnx_manage.py script  add new SP to the ECOM Server   ,it's show me this 

Traceback (most recent call last):
  File "./ecom_vnx_manage.py", line 43, in <module>
    main()
  File "./ecom_vnx_manage.py", line 40, in main
    args.ecom_ip, args.ecom_user, args.ecom_pass)
  File "./ecom_vnx_manage.py", line 14, in add_vnx
    ers = ecom_conn.EnumerateInstanceNames("EMC_SystemRegistrationService")
  File "/usr/lib/python2.6/site-packages/pywbem-0.8.4-py2.6.egg/pywbem/cim_operations.py", line 958, in EnumerateInstanceNames
    **params)
  File "/usr/lib/python2.6/site-packages/pywbem-0.8.4-py2.6.egg/pywbem/cim_operations.py", line 597, in imethodcall
    debug=self.debug)
  File "/usr/lib/python2.6/site-packages/pywbem-0.8.4-py2.6.egg/pywbem/cim_http.py", line 665, in wbem_request
    client.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 930, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 802, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/site-packages/pywbem-0.8.4-py2.6.egg/pywbem/cim_http.py", line 371, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/pywbem-0.8.4-py2.6.egg/pywbem/cim_http.py", line 474, in connect
    ret = self.sock.connect_ssl()
  File "/usr/lib64/python2.6/site-packages/M2Crypto/SSL/Connection.py", line 178, in connect_ssl
    return m2.ssl_connect(self.ssl, self._timeout)
M2Crypto.SSL.SSLError: certificate verify failed

**Comment by ktelep** [comment]
In the line where it creates the connection, add no_verification=True similar to this:

pywbem.WBEMConnection(ecom_url, (ecom_user, ecom_pass),
default_namespace="/root/emc", no_verification=True)

That should resolve the issue, but you will also need to make this change in the stats and discovery scripts too.

**Comment by fooltux** [comment]
HI ktelep 
    I have solve this problem with my job mater ’s help ,and thank you very much
    these scripts works well :) 

> 在 2016年8月24日，22:10，Kurt Telep <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> That should resolve the issue, but you will also need to make this change in the stats and discovery scripts too.
