### ISSUE TITLE
Error in "emc_vnx_stats.py" (pywbem)

### ISSUE THREAD

**Issue by kalwraith** [ktelep/EMC-Zabbix-Integration#21]
Hi ktelep
When zabbix run "emc_vnx_stats.py" item values aren't gathered.
in history, I got messages below.

Traceback (most recent call last):
  File "/KIC/emc_vnx_stats.py", line 629, in <module>
    main()
  File "/KIC/emc_vnx_stats.py", line 621, in main
    args.ecom_user, args.ecom_pass)
  File "/KIC/emc_vnx_stats.py", line 338, in hardware_healthcheck
    array_list = ecom_conn.EnumerateInstanceNames("Clar_StorageSystem")
  File "/usr/lib/python2.7/site-packages/pywbem/cim_operations.py", line 1275, in EnumerateInstanceNames
    **extra)
  File "/usr/lib/python2.7/site-packages/pywbem/cim_operations.py", line 770, in _imethodcall
    recorder=self.operation_recorder)
  File "/usr/lib/python2.7/site-packages/pywbem/cim_http.py", line 764, in wbem_request
    raise ConnectionError("Socket error: %s" % exc)
pywbem.exceptions.ConnectionError: Socket error: [Errno -2] Name or service not known

But same operation in ssh works successfully!
/KIC/emc_vnx_stats.py --serial FCNCP11090***\* --ecom_ip 127.0.0.1 --ecom_user admin --ecom_pass "#1Password" --volumes

I changed "ExternalScripts" to/KIC, so it isn't a problem.
I added "no_verification=True" in the scripts, in pywbem.WBEMConnection,
and set host's macro values ({$ECOMIP}, {$ECOMUSER}, {$ECOMPASS})

my environment is
OS: CentOS 7.2
zabbix 3.2
Python: 2.7.5
pywbem: 0.9.0

Thank you.

**Comment by kalwraith** [comment]
Oh, Sorry, I wrongly created hosts (I didn't make hostname to serial)
I recreate host and It works well!
Thank you.
